### PR TITLE
February rollup

### PR DESCRIPTION
**Pull request by c-nixon**
Rollup of all the changes that have happened on emacs/master since the last rollup. There are a fair number of threading fixes littered through the commits which will hopefully resolve some issues that people have been seeing.

### CODE REVIEW

**Comment by c-nixon** [comment]
Hmm, I can't seem to get at the failing build log. It was working on my machine (tm). I'll check tomorrow when the internet is working again.

**Comment by c-nixon** [comment]
Test eieio-test-37-obsolete-name-in-constructor condition:

    (ert-test-failed

     ((should

       (equal

	(eieio--testing "toto")

	'...))

      :form

      (equal

       [eieio-class-tag--eieio--testing]

       ("toto" 2))

      :value nil :explanation

      (different-types

       [eieio-class-tag--eieio--testing]

       ("toto" 2))))

   FAILED  38/38  eieio-test-37-obsolete-name-in-constructor

Will have to debug that later, I'm highly unsure why it's only failing on rust stable.

**Comment by c-nixon** [comment]
Cannot reproduce locally :( Any ideas?

**Comment by vodik** [comment]
For what its worth, resolves #142

**Comment by Wilfred** [comment]
Great, thanks for this. The eieio tests have been randomly failing on Travis for some time now, we should skip them on remacs and file a separate bug to follow up. I doubt it's these changes that are causing the failures.

**Comment by Wilfred** [comment]
Merged. I've opened #159 to track the eieio issue, it's affected several legitimate PRs now.

**Pull request merged**
