### PR TITLE
XML2 optional compilation support

### LINKED ISSUE #1075: Build fails when libxml2 library is absent
In case `libxml2` library is not installed, `./configure` step figures the library to be absent and as far as I understand, the corresponding C code is not built using `#define`s. But Rust code uses methods `init_libxml2_functions` in `xml.rs` file anyway and this leads to the compilation error -

```
error[E0432]: unresolved imports `crate::remacs_sys::init_libxml2_functions`, `crate::remacs_sys::parse_region`
 --> src/xml.rs:9:18
  |
9 |     remacs_sys::{init_libxml2_functions, parse_region},
  |                  ^^^^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^ no `parse_region` in `remacs_sys`. Did you mean to use `write_region`?
  |                  |
  |                  no `init_libxml2_functions` in `remacs_sys`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `remacs`.
```

Conditional compilation has to be propagated to Rust code too.

### PR DESCRIPTION
**Pull request by shaleh**
Set the feature "use-xml2" when the compilation support LIBXML2.

Closes #1075

### CODE REVIEW

**Comment by harryfei** [comment]
@shaleh 

I use `cargo build --features xxx` to do the same thing in my `webrender` branch.

I think it's cleaner than this way. It doesn't need any `Cargo.toml.in` template file.

https://github.com/harryfei/remacs/blob/webrender/configure.ac#L4930

**Comment by shaleh** [comment]
That also works with what I added.

I added the template because we will have a few of these. As a developer, I don't want to remember to pass gobs of command line options. As I have it set up a simple `cargo check` or `cargo build` will work.

**Comment by harryfei** [comment]
Okay. It makes sense.

**Comment by shaleh** [comment]
Once we are self hosting on Rust the `configure` script style may not work for us. At that point we will need to look into how we want to handle this. Asking people to edit the `default` line in `[features]` might be how we do that. But today we use configure and it makes sense to have the Rust build set up with the same options as the C build. Otherwise there is bound to be confusion.

Thanks for asking @harryfei . I should have been more explicit.

**Pull request merged**
