### PR TITLE
Porting base64-decode-string to Rust.

### PR DESCRIPTION
**Pull request by DavidDeSimone**
This commit follows the same strategy as base64-encode-string. We will farm out
the implementation of the base64 decoding to the c-layer function 'base64_decode_1'. It is good to note that 'base64_decode_1' is a strong candidate to be brought into the rust layer, maybe by an existing library. 
I believe it would make the most sense to bring 'base64_{encode/decode}_1' into rust when we port 'base64_encode_region/base64_decode_region'. 

I am also changing the debug_assert!(STRINGP(string)) in Fbase64_encode_string to be a CHECK_STRING call, as that is more inline with what the c code was doing beforehand.

### CODE REVIEW

**Comment by DavidDeSimone** [comment]
I'm afraid I don't know why that test is failing, or how my changes could have caused it. I am unable to reproduce the failure locally on my machine. If I'm reading travis correctly, it also looks like the tests passed against rust nightly. Do you have any potential insights into this @Wilfred? 

My local output is 
```
dsimone@DESKTOP-JL830NN:/mnt/c/Users/david/proj/remacs$ cd test/
dsimone@DESKTOP-JL830NN:/mnt/c/Users/david/proj/remacs/test$ make lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke
make[1]: Entering directory `/mnt/c/Users/david/proj/remacs/test'
elc=lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke.elc; \
        if ! grep '^;.*no-byte-compile: t' lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke.el > /dev/null; then
 \
          make $elc; \
        fi; \
        loadfile=lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke.el; \
        echo Testing $loadfile; \
        stat=OK ; \
        /bin/mkdir -p lisp/emacs-lisp/eieio-tests/ ; \
        EMACSLOADPATH= LC_ALL=C EMACS_TEST_DIRECTORY=.  "../src/remacs" -batch --no-site-file --no-site-lisp -L ":.
"  -l ert -l $loadfile \
          --eval "(ert-run-tests-batch-and-exit nil)"
make[2]: Entering directory `/mnt/c/Users/david/proj/remacs/test'
make[2]: `lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke.elc' is up to date.
make[2]: Leaving directory `/mnt/c/Users/david/proj/remacs/test'
Testing lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke.el
lisp/emacs-lisp/eieio-tests/eieio-test-methodinvoke.el: Obsolete name arg "" to constructor CNM-2
Running 9 tests (2017-01-22 12:06:58-0800)
   passed  1/9  eieio-test-cl-generic-1
   passed  2/9  eieio-test-method-order-list-10
   passed  3/9  eieio-test-method-order-list-3
   passed  4/9  eieio-test-method-order-list-4
   passed  5/9  eieio-test-method-order-list-5
   passed  6/9  eieio-test-method-order-list-6
   passed  7/9  eieio-test-method-order-list-7
   passed  8/9  eieio-test-method-order-list-8
next-method-p called outside of a primary or around method
next-method-p called outside of a primary or around method
   passed  9/9  eieio-test-method-order-list-9

Ran 9 tests, 9 results as expected (2017-01-22 12:06:58-0800)

make[1]: Leaving directory `/mnt/c/Users/david/proj/remacs/test'
dsimone@DESKTOP-JL830NN:/mnt/c/Users/david/proj/remacs/test$ rustc --version
rustc 1.14.0 (e8a012324 2016-12-16)
dsimone@DESKTOP-JL830NN:/mnt/c/Users/david/proj/remacs/test$ cargo --version
cargo 0.15.0-nightly (298a012 2016-12-20)
dsimone@DESKTOP-JL830NN:/mnt/c/Users/david/proj/remacs/test$
```

**Comment by Wilfred** [comment]
Yeah, I'm not sure either.

Note that the build on Travis is not using `--enable-rust-debug`, so it's using `cargo build --release`. In my experience release builds are more likely to show bugs in FFI. Your paths in the traceback suggests you're using cygwin?

It's particularly odd that beta and nightly don't have this issue. If the issue is resolved by 1.15.0, I'd be happy to just merge then. I will try to have a look at this later this week.

**Comment by DavidDeSimone** [comment]
Thanks for the response. I'll continue to hack around on this to see if I can figure out whats going on. I think you're right in that it may be a release vs debug issue.

Also I am using the new "Bash for Windows" module in Windows 10 as an experiment. I switched to my debian install, and was also unable to reproduce this test failing.

**Comment by DavidDeSimone** [comment]
So the plot for this one is thickening. I have been able to reproduce the test failure on my Debian box, however I am seeing the following conditions:

- I am only able to reproduce it under `make -j 3 check`. Just a regular `make check` never seems to trigger it. `make -j 3 check` seems to consistently trigger it BUT
- If I rebuild after getting a build that exhibits this behavior, it I rebuild with a trivial change (touching a c file or adding some minor white space to a rust file), I don't see it in a subsequent build, running either `make check`, or `make -j 3 check`. 
- Reverting the changes in this PR yields a successful build on the build box. 

Things I still don't understand:

- Why the build box seems to be failing 100% of the time, while I am only failing sometimes.

**Comment by Wilfred** [comment]
I've merged this in #114.

You were absolutely right about the tests working when you don't pass `-j 3`. I've changed our .travis.yml to do exactly that :)

**Comment by DavidDeSimone** [comment]
Thanks for following up on this, and thank you for merging. :)

**Pull request closed without merging**
