### PR TITLE
Port overlayp and buffer-live-p to rust

### PR DESCRIPTION
**Pull request by shanavas786**

### CODE REVIEW

**Comment by birkenfeld** [comment]
Looks good, just needs a `cargo fmt`

**Comment by birkenfeld** [comment]
Thanks! The remaining failure is because some test is looking for the buffer-live-p defun in C. We can just point it to another defun for now.

**Comment by shanavas786** [comment]
Exporting `Fbuffer_live_p` is not enough ?

How can we point it to another defun ?

**Comment by Wilfred** [comment]
Looks great, thank you :)

**Pull request merged**
