### PR TITLE
Revert " port byte-to-position "

### PR DESCRIPTION
**Pull request by brotzeit**
Reverts Wilfred/remacs#669

### CODE REVIEW

**Comment by shaleh** [comment]
Are you reverting this in response to #670? Have you confirmed it is the cause?

**Comment by brotzeit** [comment]
I did this preemptively, because I know how long our builds can take.

**Comment by shaleh** [comment]
On the issue I posted a link to the submitter's emacs.d. We should try to reproduce the error with that config and if possible write a test case for remacs. Your code works in the minor cases I have tried so far.

**Comment by brotzeit** [comment]
It's an error in the process sentinel. I doubt his config is the reason for it.

**Pull request closed without merging**
