### PR TITLE
Port internal_default_interrupt_process

### PR DESCRIPTION
**Pull request by jubnzv**

### CODE REVIEW

**Comment by jubnzv** [comment]
I got stuck with strange behavior of [defvar_lisp](https://github.com/Wilfred/remacs/blob/f2c45d888f5aaf0b87e456f338066a769eeb8098/rust_src/src/eval_macros.rs#L167) macro. I try to port `Vinterrupt_process_functions` with https://github.com/Wilfred/remacs/pull/1339/commits/7dc41d07da4bd1fbb771e61b47eee82c1c5b4d71, and got following error in compile-time:

```
   Compiling remacs v0.1.0 (/home/jubnzv/Dev/remacs_clean/rust_src)
error: macro expansion ignores token `{` and any following
   --> src/eval_macros.rs:168:59
    |
168 |     ($field_name:ident, $lisp_name:expr, $value:expr) => {{
    |                                                           ^
    |
   ::: src/process.rs:556:1
    |
556 | defvar_lisp!(Vinterrupt_process_functions, "interrupt-process-functions", Qnil);
    | -------------------------------------------------------------------------------- caused by the macro expansion here
    |
    = note: the usage of `defvar_lisp!` is likely invalid in item context
```

What am I doing wrong? There is only [one](https://github.com/Wilfred/remacs/blob/540879381d79f4c4b0211bc57fdd09709749a493/rust_src/src/cmds.rs#L526) `defvar_lisp` usage example and it seems to be working correct.

**Comment by daichimukai** [comment]
Running `make rustfmt` or placing `(setq rust-format-on-save t)` in `$HOME/.emacs.d/init.el` may help you to avoid rustfmt related problems.

**Comment by jubnzv** [comment]
> Running `make rustfmt` or placing `(setq rust-format-on-save t)` in `$HOME/.emacs.d/init.el` may help you to avoid rustfmt related problems.

Problems with `rustfmt` related with [docfile.rs](https://github.com/Wilfred/remacs/blob/master/rust_src/remacs-lib/docfile.rs#L166) internals.

**Comment by daichimukai** [comment]
Nice work!

**Pull request merged**
