### PR TITLE
Use declared Qt in strings.rs instead of importing from C again

### PR DESCRIPTION
**Pull request by TheKK**

### CODE REVIEW

**Comment by dpzmick** [comment]
Could also replace all uses of `Qt` with `LispObject::from_bool(true)` for less dependence on all these magical constants!

**Comment by TheKK** [comment]
Should `Qnil` also be replaced by `LispObject::constant_nil()`? The only drawback I could figure out is it's more verbose, otherwise it's the same.

**Comment by Wilfred** [comment]
@TheKK I'm happy to merge this as soon as the conflicts are fixed :)

**Comment by TheKK** [comment]
Conflict solved!

**Comment by crlf0710** [comment]
@Wilfred This is good! I actually thought about adding something like this last week. But i didn't just because i can't come up with a good name for those...

**Pull request merged**
