### PR TITLE
Port buffer string

### PR DESCRIPTION
**Pull request by krgn**
This PR addresses #875

### CODE REVIEW

**Comment by harryfei** [comment]
You should use `make rustfmt` to format rust code.

**Comment by krgn** [comment]
> You should use `make rustfmt` to format rust code.

done!

**Comment by shaleh** [comment]
@krgn there is a rust-mode setting which runs rustfmt whenever you save the buffer.

**Comment by krgn** [comment]
> @krgn there is a rust-mode setting which runs rustfmt whenever you save the buffer.

Yes, I have this set up actually, though in rustic-mode. I did some of the editing in vim though, where this didn't kick-in :laughing:

**Pull request merged**
