### PR TITLE
Port build_overlay to rust

### PR DESCRIPTION
**Pull request by shanavas786**

### CODE REVIEW

**Comment by shaleh** [comment]
OSX failure?

**Comment by nijasimelabs** [comment]
I experience the same issue in ubuntu18.04.
I guess it has something to do with `gpg`.

May be related to [this](https://emacs.stackexchange.com/questions/27841/unable-to-decrypt-gpg-file-using-emacs-but-command-line-gpg-works)

**Comment by sbillig** [comment]
The Travis mac failure is #858, so this is probably safe to merge.

**Comment by shanavas786** [comment]
Conflicts resolved

**Pull request merged**
