### PR TITLE
Port process-type

### PR DESCRIPTION
**Pull request by brotzeit**
I can't push to @leemachin branch.

close #775

### CODE REVIEW

**Comment by shaleh** [comment]
This reduces the type gymnastics some.

```
diff --git a/rust_src/src/process.rs b/rust_src/src/process.rs
index 14639fd141..f078d9e8d2 100644
--- a/rust_src/src/process.rs
+++ b/rust_src/src/process.rs
@@ -109,7 +109,7 @@ pub extern "C" fn get_process(name: LispObject) -> LispObject {
                 .name()
                 .as_string()
                 .unwrap_or_else(|| error!("Attempt to get process for a dead buffer"));
-            let proc = get_buffer_process(Some(LispBufferOrName::from(proc_or_buf)));
+            let proc = get_buffer_process_internal(b);
             if proc.is_nil() {
                 error!("Buffer {:?} has no process.", unsafe {
                     name.u.s.data as *mut libc::c_char
@@ -172,16 +172,23 @@ pub fn process_id(process: LispProcessRef) -> Option<EmacsInt> {
 /// deleted or killed.
 #[lisp_fn]
 pub fn get_buffer_process(buffer_or_name: Option<LispBufferOrName>) -> LispObject {
-    buffer_or_name
-        .and_then(|b| b.as_buffer())
-        .and_then(|buf| {
+    get_buffer_process_internal(buffer_or_name.and_then(|b| b.as_buffer()))
+}
+
+pub fn get_buffer_process_internal(buffer: Option<LispBufferRef>) -> LispObject {
+    match buffer {
+        None => Qnil,
+        Some(buf) => {
             let obj = LispObject::from(buf);
-            unsafe { Vprocess_alist }.iter_cars().find(|item| {
-                let p = item.as_cons_or_error().cdr();
-                obj.eq(p.as_process_or_error().buffer)
-            })
-        })
-        .map_or(Qnil, |item| item.as_cons_or_error().cdr())
+            unsafe { Vprocess_alist }
+                .iter_cars()
+                .find(|item| {
+                    let p = item.as_cons_or_error().cdr();
+                    obj.eq(p.as_process_or_error().buffer)
+                })
+                .map_or(Qnil, |item| item.as_cons_or_error().cdr())
+        }
+    }
 }

 /// Return the name of the terminal PROCESS uses, or nil if none.
```

**Comment by brotzeit** [comment]
Thanks. Next time just push it to my branch.

**Comment by brotzeit** [comment]
Can you post the functions without the diff. Or just push it. It's tedious to get the fixed code this way :P

**Comment by shaleh** [comment]
Forgive me if you know this, but copy the diff into a buffer and switch to `diff-mode`. Then run `C-c a` which is apply hunk to apply the parts you like.

**Comment by brotzeit** [comment]
I wouldn't have asked if I knew this I guess =)
Sounds nice, I will give it a try.

**Comment by shaleh** [comment]
Kick the build.

**Comment by brotzeit** [comment]
@shaleh Should be good.

**Pull request merged**
