### PR TITLE
move methods from lisp.rs to related files

### PR DESCRIPTION
**Pull request by brotzeit**
lisp.rs is pretty bloated because of those methods. I would suggest to move them to the file where the type is defined. If there are no objections I will also move the rest of the methods.

### CODE REVIEW

**Comment by brotzeit** [comment]
Do we really need numbers.rs AND floatfns.rs ? I just realized there is no numbers.c. I would make this one file ?

**Comment by shaleh** [comment]
I like having the float support separate. It also has more macro magic.

**Comment by shaleh** [comment]
@brotzeit check the rustformat version you have installed.

**Comment by brotzeit** [comment]
flymake tests...

**Pull request merged**
