### PR TITLE
Fix macOS 12 deprecation notices

### LINKED ISSUE #47: CC nsterm.m gives 148 macos12 deprecation warnings
```
  CC       nsterm.o
nsterm.m:233:8: warning: 'NSNumericPadKeyMask' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]
  0x41|NSNumericPadKeyMask,     0xAE,  /* KP_Decimal */
       ^~~~~~~~~~~~~~~~~~~
       NSEventModifierFlagNumericPad
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:186:35: note: 'NSNumericPadKeyMask' has been explicitly marked deprecated here
static const NSEventModifierFlags NSNumericPadKeyMask         API_DEPRECATED_WITH_REPLACEMENT("NSEventModifierFlagNumericPad", macosx(10.0, 10.12)) = NSEven...
                                  ^
[ *snip* ]
148 warnings generated.
```
Looks like this [patch](http://emacs.1067599.n8.nabble.com/PATCH-Fix-macOS-12-deprecation-notices-td406504.html) from the non-Rust version is required.

Similarly, `nsfns.m` gives 6 warnings and `nsmenu.m` gives 11 warnings

### PR DESCRIPTION
**Pull request by Wilfred**
Should fix #47.

@rogermarlow would you mind confirming this looks good?

### CODE REVIEW

**Comment by rogermarlow** [comment]
Looking better - thank you! - but still a few warnings: `nsterm.c: 3  nsmenu.c: 4 macfont.c: 4`
```
  CC       nsterm.o
nsterm.m:6191:23: warning: 'convertBaseToScreen:' is deprecated: first deprecated in macOS 10.7 - Use -convertRectToScreen: instead [-Wdeprecated-declarations]
  pt = [[self window] convertBaseToScreen: pt];
                      ^
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:930:1: note: 'convertBaseToScreen:' has been explicitly marked deprecated here
- (NSPoint)convertBaseToScreen:(NSPoint)point NS_DEPRECATED_MAC(10_0, 10_7, "Use -convertRectToScreen: instead");
^
nsterm.m:6926:10: warning: null passed to a callee that requires a non-null argument [-Wnonnull]
  [NSApp registerServicesMenuSendTypes: ns_send_types
         ^
nsterm.m:8434:52: warning: 'context' is deprecated: first deprecated in macOS 10.12 - This method always returns nil. If you need access to the current drawing context, use
      [NSGraphicsContext currentContext] inside of a draw operation. [-Wdeprecated-declarations]
                                       context: [e context]
                                                   ^
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:414:59: note: property 'context' is declared deprecated here
@property (nullable, readonly, strong) NSGraphicsContext *context NS_DEPRECATED_MAC(10_0, 10_12, "This method always returns nil. If you need access to the current drawin...
                                                          ^
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:414:59: note: 'context' has been explicitly marked deprecated here
3 warnings generated.
  CC       nsfns.o
  CC       nsmenu.o
nsmenu.m:141:26: warning: 'attachedMenu' is deprecated: first deprecated in macOS 10.2 [-Wdeprecated-declarations]
      id attMenu = [menu attachedMenu];
                         ^
/System/Library/Frameworks/AppKit.framework/Headers/NSMenu.h:269:1: note: 'attachedMenu' has been explicitly marked deprecated here
- (null_unspecified NSMenu *)attachedMenu NS_DEPRECATED_MAC(10_0, 10_2);
^
nsmenu.m:760:44: warning: 'context' is deprecated: first deprecated in macOS 10.12 - This method always returns nil. If you need access to the current drawing context, use
      [NSGraphicsContext currentContext] inside of a draw operation. [-Wdeprecated-declarations]
                               context: [e context]
                                           ^
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:414:59: note: property 'context' is declared deprecated here
@property (nullable, readonly, strong) NSGraphicsContext *context NS_DEPRECATED_MAC(10_0, 10_12, "This method always returns nil. If you need access to the current drawin...
                                                          ^
/System/Library/Frameworks/AppKit.framework/Headers/NSEvent.h:414:59: note: 'context' has been explicitly marked deprecated here
nsmenu.m:1557:62: warning: 'NSUtilityWindowMask' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]
  aStyle = NSWindowStyleMaskTitled|NSWindowStyleMaskClosable|NSUtilityWindowMask;
                                                             ^~~~~~~~~~~~~~~~~~~
                                                             NSWindowStyleMaskUtilityWindow
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:961:32: note: 'NSUtilityWindowMask' has been explicitly marked deprecated here
static const NSWindowStyleMask NSUtilityWindowMask API_DEPRECATED_WITH_REPLACEMENT("NSWindowStyleMaskUtilityWindow", macosx(10.0, 10.12)) = NSWindowStyleMaskUtilityWindow;
                               ^
nsmenu.m:1528:67: warning: conflicting parameter types in implementation of 'initWithContentRect:styleMask:backing:defer:': 'NSWindowStyleMask' (aka 'enum NSWindowStyleMask') vs
      'NSUInteger' (aka 'unsigned long') [-Wmismatched-parameter-types]
- initWithContentRect: (NSRect)contentRect styleMask: (NSUInteger)aStyle
                                                       ~~~~~~~~~~ ^
/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:297:86: note: previous definition is here
- (instancetype)initWithContentRect:(NSRect)contentRect styleMask:(NSWindowStyleMask)style backing:(NSBackingStoreType)bufferingType defer:(BOOL)flag NS_DESIGNATED_INITIALIZER;
                                                                   ~~~~~~~~~~~~~~~~~ ^
4 warnings generated.
  CC       nsselect.o
  CC       nsimage.o
  CC       macfont.o
macfont.m:222:23: warning: implicit conversion from enumeration type 'CTCharacterCollection' (aka 'enum CTCharacterCollection') to different enumeration type
      'NSCharacterCollection' (aka 'enum NSCharacterCollection') [-Wenum-conversion]
                                       collection:collection
                                                  ^~~~~~~~~~
macfont.m:289:18: warning: 'setUsesScreenFonts:' is deprecated: first deprecated in macOS 10.11 [-Wdeprecated-declarations]
  [layoutManager setUsesScreenFonts:YES];
                 ^
/System/Library/Frameworks/AppKit.framework/Headers/NSLayoutManager.h:566:16: note: property 'usesScreenFonts' is declared deprecated here
@property BOOL usesScreenFonts NS_DEPRECATED_MAC(10_0, 10_11);
               ^
/System/Library/Frameworks/AppKit.framework/Headers/NSLayoutManager.h:566:16: note: 'setUsesScreenFonts:' has been explicitly marked deprecated here
macfont.m:344:18: warning: 'setUsesScreenFonts:' is deprecated: first deprecated in macOS 10.11 [-Wdeprecated-declarations]
  [layoutManager setUsesScreenFonts:screen_font_p];
                 ^
/System/Library/Frameworks/AppKit.framework/Headers/NSLayoutManager.h:566:16: note: property 'usesScreenFonts' is declared deprecated here
@property BOOL usesScreenFonts NS_DEPRECATED_MAC(10_0, 10_11);
               ^
/System/Library/Frameworks/AppKit.framework/Headers/NSLayoutManager.h:566:16: note: 'setUsesScreenFonts:' has been explicitly marked deprecated here
macfont.m:417:22: warning: 'getGlyphsInRange:glyphs:characterIndexes:glyphInscriptions:elasticBits:bidiLevels:' is deprecated: first deprecated in macOS 10.11 - Use
      -getGlyphsInRange:glyphs:properties:characterIndexes:bidiLevels: instead [-Wdeprecated-declarations]
      [layoutManager getGlyphsInRange:(NSMakeRange (glyphIndex, 1))
                     ^
/System/Library/Frameworks/AppKit.framework/Headers/NSLayoutManager.h:580:1: note: 'getGlyphsInRange:glyphs:characterIndexes:glyphInscriptions:elasticBits:bidiLevels:' has been
      explicitly marked deprecated here
- (NSUInteger)getGlyphsInRange:(NSRange)glyphRange glyphs:(nullable NSGlyph *)glyphBuffer characterIndexes:(nullable NSUInteger *)charIndexBuffer glyphInscriptions:(nulla...
^
4 warnings generated.
  CC       terminfo.o
```

**Comment by Wilfred** [comment]
I'm open to further PRs, or if upstream Emacs is compiling cleanly, we can cherry-pick more commits. Presumably it would be one of the commits here: https://github.com/emacs-mirror/emacs/commits/emacs-25/src/nsterm.m

**Comment by rogermarlow** [comment]
OK great. Well I can confirm that upstream Emacs is compiling cleanly on macOS. I'll have a look and see.

**Comment by rogermarlow** [comment]
Bit more detail on compiling the upstream Emacs on MacOS. The master branch builds cleanly but branch emacs-25 does not, at least not on MacOS 10.12.2. We're back to 146 warnings on nsterm.m there. So any cherry picking will have to come from master. Trying that now but not really understanding the labyrinthine macro expansion arrangements, so it's somewhat trial-and-error, or trial-and-deprecation-warning :-) at the moment.

**Pull request merged**
