### PR TITLE
Implement SHA1, SHA256, SHA384, and SHA512 in Rust using ring

### PR DESCRIPTION
**Pull request by moosingin3space**
Early implementation of #80

### CODE REVIEW

**Comment by moosingin3space** [comment]
Looks like the test case failure is inconsistent. 
I'm new to the emacs codebase, how are the `sha*_stream` functions used? I'd like to be able to completely replace Emacs' own implementation of the hashes, but I didn't know what to do with the stream functions.

**Comment by moosingin3space** [comment]
Not sure why it fails with "unable to parse TOML".

**Comment by moosingin3space** [comment]
Also, what do you think I should do about SHA-224? It's not present in ring, but is needed in Emacs.

**Comment by Wilfred** [comment]
We should ask nicely for SHA224 support :) https://github.com/briansmith/ring/issues/438

In the meantime, I'd be happy to merge this once the conflicts are fixed.

**Comment by moosingin3space** [comment]
I'd like to try and get rid of the last usage of the Emacs SHA-1 implementation, which I left in for now.

**Comment by Wilfred** [comment]
@moosingin3space friendly ping.

**Comment by moosingin3space** [comment]
@Wilfred I'm sorry, I became pretty busy with school. I'll give it a shot at replacing the last SHA-1 usages (and removing all the C code I can) this week!

**Comment by Wilfred** [comment]
This is all looking good, I think the way you've structured it is great.

I don't think Ring is going to be a good fit for us though. It will be awkward supporting SHA224 since upstream doesn't want to support it. Ring is also difficult to build on Windows.

Whilst [dagenix/rust-crypto](https://github.com/DaGenix/rust-crypto/) has been abandoned, there's a [rust-crypto](https://github.com/RustCrypto/hashes) project that is actively maintained. The code is pure Rust, so it should be easier to work with. They have a [sha2 crate](https://crates.io/crates/sha2) which I think would be a great fit.

**Comment by Wilfred** [comment]
Continuing work in #162.

**Pull request closed without merging**
