### PR TITLE
Clean up the rest of the deprecated lisp.rs functions

### PR DESCRIPTION
**Pull request by birkenfeld**
(Again, this depends on a previous PR's commits, #192)

### CODE REVIEW

**Comment by jeandudey** [comment]
Please fix the `cargo fmt` errors so the build can continue properly.

**Comment by birkenfeld** [comment]
I guess I have to update my rustfmt then - I definitely did cargo fmt before submitting this one!

(That reminds me to create a script or makefile target to do that automatically for all cargo projects.)

**Comment by birkenfeld** [comment]
Ok, should be fixed with 0.8.4. I also changed the tramp tests as @Wilfred suggested to get a green light on OSX.

**Comment by Wilfred** [comment]
I believe these changes were merged as part of #203, so I'm closing this.

**Pull request closed without merging**
