### PR TITLE
Correct deprecated AppKit Color API

### PR DESCRIPTION
**Pull request by gganley**
Ever since the release macOS 10.14 Mojave there have been issues running the GUI of Emacs. This is taken from GNU Emacs to replace the deprecated APIs

### CODE REVIEW

**Comment by shaleh** [comment]
Bah. One more time.

**Comment by gganley** [comment]
These were cherry picked from emacs/scratch/ns-drawing. Let me see if they were merged into master.

**Comment by shaleh** [comment]
Does emacs master work? If so, we can continue to port back from it. If not, then we need this cherry pick

**Comment by shaleh** [comment]
Does emacs master work? If so, we can continue to port back from it. If not, then we need this cherry pick

**Comment by gganley** [comment]
Just to clarify, are you asking if the emacs master has the depreciation issue?

**Comment by shaleh** [comment]
Yes, sorry if I was not clear.

**Comment by gganley** [comment]
I compiled emacs HEAD from brew and it works just fine, would you like the commands I ran and pictures of it running or is this sufficient.

**Comment by shaleh** [comment]
Just knowing that emacs HEAD works is enough. That means there are commits in HEAD that we can backport to our tree. Thanks for doing the legwork @gganley.

A potentially quick way to identify the fix is to find the .m files here https://github.com/emacs-mirror/emacs/tree/master/src and then look at their commit history. Hopefully a commit message is clear enough and we can cherry pick those commits.

**Comment by gganley** [comment]
So you'd rather me cherry-pick from master rather than this branch?

**Comment by shaleh** [comment]
Yes we would. It makes the merges later easier.

**Comment by shaleh** [comment]
@gganley @daichimukai what do we do with this PR?

**Comment by daichimukai** [comment]
@ggnaley Now necessary commits seems to be merged in GNU Emacs's master commit. Are you interested in cherry-picking?

**Comment by gganley** [comment]
Dupe of #1338, they cherry picked it already.

**Comment by daichimukai** [comment]
Closing due to that #1338 has merged.

**Pull request closed without merging**
