### PR TITLE
[WIP] Port Remacs Lisp_Hash_Table to use FnvHashMap. 

### PR DESCRIPTION
**Pull request by DavidDeSimone**
This is the  WIP commit for https://github.com/Wilfred/remacs/issues/276. 

TODO List:
- [x]  Manually derive PartialEq and Eq for HashableLispObject
  - [x] Implement user defined hash function and cmp function. 
- [x] Add "purecopy" functionality. 
- [x] Remove def. of Lisp_Hash_Table from C/Rust
- [x] Rename all "LispHashMap" functions to "LispHashTable" equiv. 
  - [x] Make "LispHashTable" be properly tagged as a HashTable pseudovector, with proper sizing. 
  - [x] Convert "get_hash_table_or_error" to return a LispHashTableRef that references a LispHashTable, instead of a Lisp_Hash_Table. 
- [x] Have "LispHashTable" be allocated by the Lisp GC, and managed by the Lisp GC
  - [x] Add a "hashtable_finalize" method for the cleanup at the rust layer.
- [x] Add weak table support. 
- [ ] Handle profiler.c's custom hash/cmp function for it's hash_table_test
- [x] Fix temacs build stage segfaults
- [ ] Final test/integration pass
- [ ] Final performance/benchmarking pass

### CODE REVIEW

**Comment by DavidDeSimone** [comment]
So right now I am dealing with some problems in the _unexec_ codepath. temacs builds and runs fine, however attempting to access a particular allocation is failing when running bootstrap-emacs. 

The Vcoding_system_hash_table Hash Table seems to be valid when running temacs, but is not valid when running bootstrap-emacs. Via GDB, I can verify the state of this hash table. Internally, it's rust HashMap looks like: 

table = {capacity_mask = 1023,  size = 899, hashes = 0x7fffee429010}

When running temacs, the 'hashes' memory address is a valid address that I can deference. However, running bootstrap-emacs, that address is no longer valid, and attempting to deference it will lead to a seg fault. This address is not always the same, however it seems to always be in the 0x7fffe.. range. My first thought was there was some trouble mixing Rust's default allocator, with the unexec flow, so I switched remacs over to globally using malloc, similar to how we use unexec_malloc on OSX. However, this has not helped. Interestingly enough, the vector that stores the keys and values of the hash map always seems to be valid. It is ONLY this hashmap's internal hash data that is invalid. It's also interesting to note that this is not happening for ALL hashmaps. Most of them seem to work fine in the dumped bootstrap-emacs.  

I am going to keep investigating, however I am open to community ideas on what paths I should go down on this.

**Comment by DavidDeSimone** [comment]
After further investigation, it turns out that sometimes our HashMaps will have indivdual allocations above M_MMAP_THRESHOLD, which is set to 64 * 1024 in alloc.c. Since the allocation is above that threshold, it will use mmap over brk/sbrk, and thus will not be copied into the new bss segment when emacs unexec's. 

Looking back, it seems obvious, but this was a bit of a doozy to figure out haha.

**Comment by DavidDeSimone** [comment]
So this is making good progress, and all but one testing is passing! This ended up being slightly more difficult then I anticipated, due to the fact that most of the C-layer makes a lot of assumptions about the internals of HashTables and how they work. 

I need to spend some time benchmarking and optimizing this guy to make sure that we are still getting the advertised gains, but I hope to have this PR ready for wide-review by the end of the month.

**Comment by DavidDeSimone** [comment]
After a long journey, and a lot of code, I am going to advise that we do *not* use Rust's HashMap at this time, and that we make a straight port of existing HashTable code. 

Reasons:

- While the lisp layer has a very clean API for interacting with a HashTable, the C layer makes a lot of assumptions on the structure of the HashTable. 
- There are certain operations that update the key of the hash table in place. While I have a possible way of doing this, I am very leery of it, because we are making Rust's HashMap do something it explicitly doesn't support. 
- In order to support APIs that the C code bases uses to interact with hash tables (including an API to update a key/value in constant time by directly writing into it's private data vector), we have to maintain a lot of boilerplate. 
- After testing and playing around with the current code writing, I believe there is a strong chance that this refactor will introduce divergence and incompatibility between upstream in the future. 

If no one objects, I am going to close this PR, and will open on a PR that focuses on converting the existing HashTable from C to Rust piecemeal.

**Comment by brotzeit** [comment]
If you think that's the best solution do it. Maybe we should avoid to make things too complicated for now.

**Comment by Wilfred** [comment]
Whilst this hasn't resulted in us landing code that uses FnvHashMap, it's a really useful conclusion. Thanks for exploring this so thoroughly!

Could you comment on where the code assumes that it can mutate keys in hash tables? I would have thought we will eventually want to refactor that out.

**Pull request closed without merging**
