### PR TITLE
Sync Rust version of Dockerized environment

### PR DESCRIPTION
**Pull request by daichimukai**
#1286 may have caused by incompatible version of Rust toolchain in Dockerfile.

### CODE REVIEW

**Comment by shanavas786** [comment]
Did this change fix docker build issues ?

I doubt we need to add `clang libclang-dev` to dependencies as well

**Comment by daichimukai** [comment]
@shanavas786 Is there build issue on docker env and not enough what is in Dockerfile already? At least I could build docker image and, after building Remacs, run `docker-compose exec remacs ./src/remacs -Q`.

**Comment by shanavas786** [comment]
It was just a doubt as `clang` is missing from `Dockerfile` for `fedora`

**Comment by shaleh** [comment]
@shanavas786 I think that is more because the Fedora Docker has seen less attention.

**Comment by shaleh** [comment]
In a perfect world where we had tons of resources, we would run all of the docker images in Travis. Perhaps not on every push but on every merge. We would also have a working Windows env too.

**Comment by daichimukai** [comment]
I opened an issue for build dep on Fedora. Thanks for noticing :+1:

**Pull request merged**
