### PR TITLE
there's no longer any need for these accessors, now that we have bindgen

### PR DESCRIPTION
**Pull request by db48x**

### CODE REVIEW

**Comment by shaleh** [comment]
We may need to find ways to take less time.

For right now, I think we can disable the "no window system" compilation so we only build twice.

**Comment by db48x** [comment]
I don't know. It didn't exceed the overall time limit, but instead stalled and didn't produce any output for 10 minutes. Dropping one of the build steps wouldn't fix that.

**Comment by db48x** [comment]
Looks like `python-tests` takes a long time on my computer as well. I don't know how long yet, however.

**Comment by db48x** [comment]
In fact, it looks like it's deadlocked. The remacs process has called `read` and is waiting, while both python processes have called `select` and are waiting.

**Comment by db48x** [comment]
Hrm, that time it didn't deadlock. There are half a dozen errors though, all of them "Error reading from stdin".

**Comment by brotzeit** [comment]
Any chance this is related to #801 ?

**Comment by db48x** [comment]
It shouldn't be, unless I did something wrong. Why do you ask?

**Comment by brotzeit** [comment]
Because that PR fixed process related issues.

**Pull request merged**
