### PR TITLE
upgrade rust toolchain into 2018-11-03

### PR DESCRIPTION
**Pull request by harryfei**

### CODE REVIEW

**Comment by harryfei** [comment]
I reformat the code already. However, this CI is still failed. It's really odd.

**Comment by harryfei** [comment]
I found the root cause. I forget to checkout from latest master when I do this change.

**Comment by shaleh** [comment]
Too new for me on MacOS.

> toolchain 'nightly-2018-11-03-x86_64-apple-darwin' does not have the binary `rustfmt`

**Comment by harryfei** [comment]
Just for confirming, did you install it manually by `rustup component add rustfmt-preview`?

**Comment by shaleh** [comment]
No. I ran `rustup update`.

**Comment by harryfei** [comment]
I found that we need to install the `rustfmt` manually everytime we upgrade the toolchain in `remacs`.

**Comment by jaccarmac** [comment]
The rustfmt reinstall is a minor annoyance but perhaps worth moving the install into a bootstrap script? It's already in CI after all.

**Pull request merged**
