### PR TITLE
May rollup

### PR DESCRIPTION
**Pull request by jeandudey**
Rollup of all the changes that have happened on emacs/master.

We should do rollups more frequently (weekly?) because the more code we move to Rust the more conflicts that are generated.

P.S: I got this error when trying to build on my machine:
```
In toplevel form:
textmodes/texinfo.el:35:30:Error: Face height does not produce a positive integer: tex-suscript-height
Makefile:302: fallo en las instrucciones para el objetivo 'textmodes/texinfo.elc'
```
I'll check if it fails on travis too and do some debugging.

### CODE REVIEW

**Comment by Wilfred** [comment]
We're seeing the same error on Travis:

```
In toplevel form:
textmodes/texinfo.el:35:30:Error: Face height does not produce a positive integer: tex-suscript-height
```

I wonder if it's just a typo: tex-su**b**script-height perhaps?

**Comment by jeandudey** [comment]
@Wilfred red i'm reading the code in `lisp/textmodes/tex-mode.el` and everything seems to be fine, however the `tex-suscript-height` function calls various functions that are defined in the rust codebase (`ceiling`, `max`, `integerp` and `*`), i thought if there were changes in upstream Emacs to those functions that changed their behaviour leaving our functions outdated.

**Comment by Wilfred** [comment]
Interestingly, there have been some changes to arithmetic such as https://github.com/emacs-mirror/emacs/commit/207ee94b1d1f3cbe5ddd87a4cdfae17e5ad8419d . This commit is odd because it's on GNU Emacs master but not in this rollup branch.

I'm trying to reproduce this issue locally so I can play with it.

**Comment by Wilfred** [comment]
You're absolutely right! On this branch, we get the following behaviour:

```
ELISP> (max 0.0 8.0)
1.0
```

Yikes! I'll dig into this some more, but feel free to play with it too :)

**Comment by birkenfeld** [comment]
Superseded by #227.

**Pull request closed without merging**
