### PR TITLE
macOS binary should be called Remacs.app

### LINKED ISSUE #272: The invocation-name is still "Emacs" for Emacs.app on macOS
The text-mode Emacs gives `"remacs"` as expected

    $ src/remacs -Q -nw

However, the graphic Emacs still gives `"Emacs"`

    $ open nextstep/Emacs.app --args -Q

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes #272.

I think this is correct. If Travis CI is happy, I'll find a mac to test this on.

### CODE REVIEW

**Comment by benjamreynolds** [comment]
@Wilfred do you need this tested on a mac? I would be happy to accommodate.

**Comment by Wilfred** [comment]
Sorry for the delay!

@benjamreynolds yes, if you could give this a try, that would be really useful :). I don't have access to a Mac very often.

**Comment by benjamreynolds** [comment]
@Wilfred, still getting around to this. I had some build errors to work out last time I tried and ended up punting for a while.

**Comment by benjamreynolds** [comment]
Looks like this is still building an Emacs.app binary 😞

**Comment by Wilfred** [comment]
Superseded by #471.

**Pull request closed without merging**
