### PR TITLE
Some functions moved to Rust

### PR DESCRIPTION
**Pull request by birkenfeld**
This is my first venture into remacs, please review carefully. Thanks :)

### CODE REVIEW

**Comment by jeandudey** [comment]
Hi! thanks for the contribution :+1:, currently i don't have time to review your PR but i'll do it soon. Also it would be nice if you do a rebase and have a single commit :smile:.

**Comment by birkenfeld** [comment]
Sure, single commit coming up :) I'll also fix the travis run.

**Comment by birkenfeld** [comment]
Can't debug the OSX failure, sorry.

**Comment by Wilfred** [comment]
Awesome! This looks great but I'll give you a proper review shortly. I particularly like your Rust iterator that does the classic lispy hare and tortoise movement through lists.

I don't feel strongly about commit granularity, but I'd prefer that styling and functionality changes were separate at least. No worries about changing this PR though.

I'll have a look at the failing OS X build too.

**Comment by Wilfred** [comment]
OK, I've read through the code, and it all looks lovely. 👍 

The failure on OS X is just tramp. I'm happy for us to skip the tramp tests on OS X (upstream GNU Emacs doesn't have any CI on OS X to my knowledge).

@birkenfeld how do you want to proceed? I notice that #192 includes these commits.

**Comment by birkenfeld** [comment]
Since as you say this is included in #192, I'll just close this one.

I really miss (from Gerrit style reviews) the ability to submit dependent commits and have them reviewed individually.

**Pull request closed without merging**
