### PR TITLE
Port callproc.c from emacs 25

### PR DESCRIPTION
**Pull request by vodik**
I back-ported emacs 25 callproc.c back into remacs, while preserving existing cleanup efforts. With this patch in place, `call-process` correctly returns process exit codes, fixing #142.

I want to emphasis this is the first time I've ever looked at the emacs source code and don't have the slightest idea what part of this is the actual fix. But might not be a bad idea to merge since it seems like emacs has cleaned it up a bit. For example `reallocate_fd` is dead code.

### CODE REVIEW

**Comment by Wilfred** [comment]
Thanks for your contribution!

Remacs is a fork of the master branch of GNU Emacs, so it's effectively Emacs 26. Merging patches from Emacs 25 could cause pain when we next merge in GNU Emacs master.

Could you identify which commits this is? git-blame should be able to help you here. Looking at master on GNU Emacs, I suspect it's https://github.com/emacs-mirror/emacs/commit/b4c9f9120d8b0da0593f2fbde69b40374f56451d .

**Comment by vodik** [comment]
Aaaand it isn't 25. Brain fart, my bad. I meant 26.

I pulled this straight from a emacs-git source tree I have kicking around. Teaches me to write PRs late in the night.

So, first thing I did was look at the log for callproc.c and I didn't see anything interesting there. In fact, that commit you suspect to be the problem isn't in the history.

I'll see if I can find anything more later tonight, at the very least I'll fix up the commit to correctly identify the version.

**Comment by c-nixon** [comment]
#158 has the upstream commit containing the immediate_quit changes, along with everything else that went into emacs/master in the last month.

Could you test that PR? Being able to pull it all in at once makes the rollup merges much easier :)

**Comment by vodik** [comment]
Sure, just a sec.

**Comment by vodik** [comment]
The issue is fixed with #158, so I'll close this PR. Thanks for all the help!

**Pull request closed without merging**
