### PR TITLE
Let's update Travis for Linux.

### PR DESCRIPTION
**Pull request by shaleh**

### CODE REVIEW

**Comment by db48x** [comment]
slow build

**Comment by shaleh** [comment]
Slow build death againnnnn

**Comment by shaleh** [comment]
OSX continues to fail part way through the build. This last run it did not even succeed in downloading the requirements.

**Comment by shaleh** [comment]
And again...

**Comment by db48x** [comment]
or it could just never start the mac builds.

**Comment by shaleh** [comment]
#736 resolves the appveyor problem. Maybe @Wilfred just merges these two commits as it?

**Comment by Wilfred** [comment]
:tada: :tada:

Awesome. FWIW we're only requiring Travis to be green on PRs, Appveyor is optional.

**Pull request merged**
