### PR TITLE
Extract docstrings for interactive help, update find-func to find Rust functions

### PR DESCRIPTION
**Pull request by birkenfeld**
Includes updated commits from #68.

This lets us:

* put Rust subr docstrings in etc/DOC
* automatically generate usage examples for ordinary fns
* find the Rust functions in the source (thanks to Chris' patches)
* generate globals.h entries for lisp_fns.

### CODE REVIEW

**Comment by birkenfeld** [comment]
Thanks! Tomorrow I should be able to restore the original branch with smaller commits where the failure started to occur.

**Comment by birkenfeld** [comment]
@Wilfred this should contain the failure and has smaller commits: https://github.com/birkenfeld/remacs/tree/pre_rebase

**Comment by birkenfeld** [comment]
Ok, I "procured" a Mac and looked at this: it seems that the change to disable tramp tests was incomplete. When I enable the tests again the tests run fine 🎊 

 (Possibly a result of the integer overflow fix that comes after the Tramp/Darwin commit.)

I also committed this change to the branch here, let's see if Travis agrees.

**Comment by birkenfeld** [comment]
The Mac build is green now, but the Linux one had a timeout compiling syntex.

**Comment by Wilfred** [comment]
@birkenfeld Sorry about that. I've been working on pinning rustfmt, so we stop inconveniencing our amazing contributors by new rustfmt versions coming out mid PR.

As part of this, I cleared the Travis cache a few minutes ago. I've restarted the linux job, so that should fix it.

**Comment by birkenfeld** [comment]
Ah nice. It just seems 0.9.1 is not released yet :)

**Comment by Wilfred** [comment]
> Ah nice. It just seems 0.9.1 is not released yet :)

Yep, I wanted to confirm it was honouring my `--vers` :)

**Comment by birkenfeld** [comment]
Doesn't seem to get any further yet...

**Comment by Wilfred** [comment]
Based on https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

perhaps we should try `travis_wait 30 cargo install ...`? I suspect that as soon as it's succeeded on one branch, the others will work.

**Comment by Wilfred** [comment]
Looks like #207 (which apparently hasn't shared the cache with this PR) *just* managed to squeeze within the 10 minute window:

```
   Compiling syntex_errors v0.59.1
   Compiling syntex_syntax v0.59.1
    Finished release [optimized] target(s) in 751.39 secs
```

**Comment by birkenfeld** [comment]
Yay!

**Comment by Wilfred** [comment]
Fantastic! Thank you very much :)

**Pull request merged**
