### PR TITLE
Disable OSX until Travis CI is stable.

### PR DESCRIPTION
**Pull request by shaleh**

### CODE REVIEW

**Comment by Wilfred** [comment]
We don't need to go this far. We could either:

* mark OS X as allowed to fail but still run it on Travis
* compile Remacs on Travis but don't bother running tests
* change the unreliable tests to not run on OS X, similar to #160

I think it's only a few tests that regularly fail. Have you seen broader failures?

**Comment by shaleh** [comment]
The issue is that OSX is not loading at all. Not that the tests are always failing.

**Comment by shaleh** [comment]
Look at my open PRs for the eval changes. They are all hung waiting for OSX to run.

**Comment by shaleh** [comment]
Appears stable now. Dropping this PR.

**Pull request closed without merging**
