### PR TITLE
Update to a later version of GNU Emacs upstream

### LINKED ISSUE #840: (Feature request) Update with Flymake changes from upstream GNU Emacs
`eglot` is a LSP frontend that depends on recent changes to Flymake. The present version of Remacs does not have these changes, so running `M-x eglot` in Remacs gives an error of `flymake--diag is not a struct`.

`flymake--diag` was renamed from `flymake-ler` at https://github.com/emacs-mirror/emacs/commit/ae64bf12a865d5d40b7541af0da9b971936994ec.

### PR DESCRIPTION
**Pull request by Wilfred**
This was a particularly straightforward update, we should do more of these :)

Fixes #840.

### CODE REVIEW

**Comment by Wilfred** [comment]
Argh, perhaps not as straightforward as I'd hoped. My merge resurrected `marker.c` and the reference to `marker.o` in Makefile.in.

I've fixed those issues, but there's still a linker issue. I also want to investigate why that happened, to ensure I've not screwed up anything else.

**Comment by Wilfred** [comment]
Turns out it it's even more straightforward if I don't delete needed files like marker.c :)

Builds cleanly now.

**Comment by Wilfred** [comment]
Skipping this flymake test:

```
(ert-deftest different-diagnostic-types ()
  "Test GCC warning via function predicate."
  (skip-unless (and (executable-find "gcc") (executable-find "make")))
  (let ((flymake-wrap-around nil))
    (flymake-tests--with-flymake
        ("errors-and-warnings.c")
      (flymake-goto-next-error)
      (should (eq 'flymake-error (face-at-point)))
      (flymake-goto-next-error)
      (should (eq 'flymake-note (face-at-point))) ;; <-- fails here
      (flymake-goto-next-error)
      (should (eq 'flymake-warning (face-at-point)))
      (flymake-goto-next-error)
      (should (eq 'flymake-error (face-at-point)))
      (flymake-goto-next-error)
      (should (eq 'flymake-warning (face-at-point)))
      (flymake-goto-next-error)
      (should (eq 'flymake-warning (face-at-point)))
      (should-error (flymake-goto-next-error nil nil t)))))
```

I suspect it's just the version of gcc on travis isn't reporting a note on that line.

**Comment by shaleh** [comment]
@Wilfred what is your status on this?

**Comment by Wilfred** [comment]
Remacs is building. There's a flymake bug with a missing function, that was fixed in 042b3cfbd2ed9da2404d1b3b8ab786c92b507d42. That commit is later, but I've just cherry-picked it.

The only other issue is a gpg failure on macOS, which looks like #858.

**Comment by brotzeit** [comment]
> The only other issue is a gpg failure on macOS, which looks like #858.

I also get this error on arch linux for some time.

**Comment by harryfei** [comment]
Looks good.

**Pull request merged**
