### PR TITLE
Add `make clippy`.

### PR DESCRIPTION
**Pull request by shaleh**
Update tree from clippy suggestions.
Run clippy in Travis, but it is advisory only.

### CODE REVIEW

**Comment by shaleh** [comment]
hmm, my attempt at not having Clippy block the build did not work....

**Comment by shaleh** [comment]
hmm, now the OSX checks are not allowed to fail....

**Comment by nickdrozd** [comment]
I don't know how much it matters, but the existing pattern would have you add the clippy command to `configure.ac` and then substitute in the makefiles:

```diff
modified   Makefile.in
@@ -82,6 +82,7 @@ CARGO_BUILD=@CARGO_BUILD@
 CARGO_CLEAN=@CARGO_CLEAN@
 CARGO_TEST=@CARGO_TEST@
 CARGO_FLAGS=@CARGO_FLAGS@
+CARGO_CLIPPY=@CARGO_CLIPPY@
 
 ### These help us choose version- and architecture-specific directories
 ### to install files in.
@@ -954,6 +955,11 @@ check check-maybe check-expensive: have-tests all
 	$(MAKE) -C src $@
 	$(MAKE) -C test $@
 
+clippy:
+	$(MAKE) -C src $@
+
+.PHONY: clippy
+
 dist:
 	cd ${srcdir}; ./make-dist
 
modified   configure.ac
@@ -4993,9 +4993,11 @@ CARGO="cargo"
 CARGO_BUILD="$CARGO build"
 CARGO_CLEAN="$CARGO clean"
 CARGO_TEST="$CARGO test"
+CARGO_CLIPPY="$CARGO clippy"
 
 AC_SUBST(CARGO_BUILD)
 AC_SUBST(CARGO_CLEAN)
+AC_SUBST(CARGO_CLIPPY)
 
 AC_ARG_ENABLE(rust-debug,
 [AS_HELP_STRING([--enable-rust-debug],
modified   src/Makefile.in
@@ -345,6 +345,7 @@ CARGO_BUILD=@CARGO_BUILD@
 CARGO_CLEAN=@CARGO_CLEAN@
 CARGO_TEST=@CARGO_TEST@
 CARGO_FLAGS=@CARGO_FLAGS@
+CARGO_CLIPPY=@CARGO_CLIPPY@
 
 ifeq ($(findstring --release,$(CARGO_FLAGS)),--release)
 CARGO_BUILD_DIR=release
```

**Comment by shaleh** [comment]
Thanks @nickdrozd

**Comment by nickdrozd** [comment]
Not sure how to push to a PR, but my recent merges introduced a small conflict.

```diff
modified   rust_src/src/keymap.rs
@@ -592,7 +592,7 @@ pub extern "C" fn describe_vector_princ(elt: LispObject, fun: LispObject) {
 #[lisp_fn(min = "1", name = "describe-vector")]
 pub fn describe_vector_lisp(vector: LispObject, mut describer: LispObject) {
     if describer.is_nil() {
-        describer = intern("princ");
+        describer = LispObject::from(intern("princ"));
     }
     unsafe { specbind(Qstandard_output, current_buffer()) };
     if !(vector.is_vector() || vector.is_char_table()) {
```

**Comment by shaleh** [comment]
I have a PR up to fix it.

**Comment by shaleh** [comment]
@nickdrozd when #1062 lands can you kick this PR too please?

**Pull request merged**
