### PR TITLE
Fix LispMisc type.

### PR DESCRIPTION
**Pull request by jeandudey**
There are a couple of errors when compiling for a 32 bits architecture.
This commit solves these errors.

### CODE REVIEW

**Comment by Wilfred** [comment]
Looks good! Would it be possible to update the Travis configuration so we build against 32-bit architectures too?

**Comment by Wilfred** [comment]
See also #35, which is also looking at this issue.

**Comment by jeandudey** [comment]
I think 32 bits build cannot be enabled since `pthread` (for 32 bits) and other Rust required libraries aren't
on Travis CI.

**Comment by jeandudey** [comment]
I tested #35 and i think it should be merged first, since it haves a nice solution for type generation. But it still have these errors when compiling for 32 bits:

```
   Compiling remacs v0.1.0 (file:///home/jeandudey/rust-projects/remacs/rust_src)
error[E0512]: transmute called with differently sized types: *const libc::c_void (32 bits) to lisp::LispMisc (64 bits)
   --> /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:472:14
    |
472 |     unsafe { mem::transmute(XUNTAG(a, LispType::Lisp_Misc)) }
    |              ^^^^^^^^^^^^^^ transmuting between 32 bits and 64 bits

error[E0512]: transmute called with differently sized types: lisp::LispMisc (64 bits) to *const lisp::LispMiscAny (32 bits)
   --> /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:478:14
    |
478 |     unsafe { mem::transmute(XMISC(a)) }
    |              ^^^^^^^^^^^^^^ transmuting between 64 bits and 32 bits

error[E0512]: transmute called with differently sized types: lisp::LispMisc (64 bits) to *const marker::LispMarker (32 bits)
   --> /home/jeandudey/rust-projects/remacs/rust_src/src/lisp.rs:507:14
    |
507 |     unsafe { mem::transmute(XMISC(a)) }
    |              ^^^^^^^^^^^^^^ transmuting between 64 bits and 32 bits

error: aborting due to 3 previous errors

error: Could not compile `remacs`.

To learn more, run the command again with --verbose.
```

**Comment by jeandudey** [comment]
@Wilfred this is now ready to be merged.

**Comment by Wilfred** [comment]
Marvellous, thanks for looking at #35 too so we know there isn't overlap.

**Pull request merged**
