### PR TITLE
remove CONTRIBUTORS file

### PR DESCRIPTION
**Pull request by brotzeit**
IMO we don't need this file. Last commit was almost 1 year ago.

### CODE REVIEW

**Comment by shaleh** [comment]
How do we generate a liat without including any Emacs devs?

**Comment by brotzeit** [comment]
No idea.

**Comment by nickdrozd** [comment]
`git log --format='%an' -- '*.rs' | sort -u`

That's not perfect -- some people are listed more than once because of committing under multiple names, and someone who made only Lisp / C modifications without touching Rust would not be listed. But I would think it's mostly pretty close.

**Comment by shaleh** [comment]
```
Aaron Jacobs <atheriel@gmail.com>
Alexander Kuleshov <kuleshovmail@gmail.com>
Ashton Kemerling <ashtonkemerling@gmail.com>
Athene Noctua <steinuil@users.noreply.github.com>
Bjarte Johansen <bjarte.johansen@gmail.com>
Brayden Banks <me@bb010g.com>
Brian Leung <bkleung89@gmail.com>
Chaitanya Koparkar <ckoparkar@gmail.com>
Chris Nixon <chris.nixon@sigma.me.uk>
Chris Overcash <covercash2@gmail.com>
CrLF0710 <crlf0710@gmail.com>
Daniel Brooks <db48x@db48x.net>
Daniel Luna <dancluna@gmail.com>
David DeSimone <david.desimone@bigfishgames.com>
David DeSimone <djd231@scarletmail.rutgers.edu>
David DeSimone <lord.good.mail@gmail.com>
David Zmick <dpzmick@gmail.com>
DavidDeSimone <djd231@scarletmail.rutgers.edu>
DavidDeSimone <lord.good.mail@gmail.com>
Erik Anderson <erikbpanderson@gmail.com>
Fangyuanziti <tiziyuanfang@gmail.com>
Felix S. Klock II <pnkfelix@pnkfx.org>
Femi Agbabiaka <femianthonyagbabiaka@gmail.com>
GT Barry <gaak99@gmail.com>
Georg Brandl <g.brandl@fz-juelich.de>
Georg Brandl <georg@python.org>
Glenn Barry <gaak99@gaak99.com>
Greg Katz <gregkatz@gmail.com>
Gritsak Oleg <oleg@teasernet.com>
Harry Fei <tiziyuanfang@gmail.com>
Hoàng Đức Hiếu <hdhoang@hdhoang.space>
Jacob MacDonald <jaccarmac@gmail.com>
Jamie McClymont <jamie.mcclymont@gmail.com>
Jason Reed <jcreed@gmail.com>
Jean Pierre Dudey <jeandudey@hotmail.com>
John Soo <jsoo1@asu.edu>
Kai Middleton <kai.middleton@gmail.com>
Karlo Licudine <accidentalrebel@gmail.com>
Karsten Gebbert <k@ioctl.it>
Kyo91 <sam.sam.42@gmail.com>
Ludwig PACIFICI <ludwig@lud.cc>
Mark Feller <mjfeller1992@gmail.com>
Martin Feckie <mfeckie@gmail.com>
Michael Walker <mike@barrucadu.co.uk>
Miles Yucht <mgyucht@gmail.com>
Nathan Moos <moosingin3space@gmail.com>
Nick Drozd <nicholasdrozd@gmail.com>
Nitish Chandra <nitishchandrachinta@gmail.com>
Paul Eggert <eggert@cs.ucla.edu>
Peter DeLong <petersdelong@gmail.com>
R. Bernstein <rocky@users.noreply.github.com>
Raimon Grau <raimonster@gmail.com>
Robbert van der Helm <mail@robbertvanderhelm.nl>
Romanos <rski@users.noreply.github.com>
Romanos Skiadas <rom.skiad@gmail.com>
Sean 'Shaleh' Perry <shaleh@speakeasy.net>
Sean Perry <shaleh@speakeasy.net>
Shanavas M <shanavas.m2@gmail.com>
Shanavas M <shanavas@disroot.org>
Sieu Tsoi <sieut@umich.edu>
Tony Day <tonyday567@gmail.com>
Wilfred Hughes <me@wilfred.me.uk>
Yaroslav <Yarikx@gmail.com>
Yaroslav Heriatovych <Yarikx@gmail.com>
Ying-Ruei Liang(KK) <thumbd03803@gmail.com>
Zajcev Evgeny <zevlg@yandex.ru>
brotzeit <brotzeitmacher@gmail.com>
brotzeit <fritz.stelzer@cancom.de>
clemensw <clemensw@users.noreply.github.com>
dalz <25228125+dalz@users.noreply.github.com>
galczo5 <kamil.galek@gmail.com>
leungbk <bkleung89@gmail.com>
mjfeller <mjfeller@users.noreply.github.com>
nitishch <nitishchandrachinta@gmail.com>
pipcet <pipcet@users.noreply.github.com>
rocky <rb@dustyfeet.com>
shanavas <shanavas.m2@gmail.com>
wizmer <ben.coste@gmail.com>
Óscar Nájera <hello@oscarnajera.com>
Óscar Nájera <najera.oscar@gmail.com>
```

Yeah, a few dupes, not too shabby.

**Pull request merged**
