### PR TITLE
port message-box

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by nickdrozd** [comment]
Ha, I had this one on my todo list for today!

Is it possible to run it in a test?

**Comment by nickdrozd** [comment]
@shaleh Is there a reason we're using `CString::new` etc instead of `"OK".as_ptr() as *const ::libc::c_char`? That seems to work just as well.

**Comment by brotzeit** [comment]
@nickdrozd I will add tests.

**Comment by nickdrozd** [comment]
> @shaleh Is there a reason we're using `CString::new` etc instead of `"OK".as_ptr() as *const ::libc::c_char`? That seems to work just as well.

Actually it does not work just as well.

**Comment by shaleh** [comment]
@nickdrozd keep in mind _all_ allocations that are visible to the C code are made in the C code. We are bound by the Lisp Garbage Collector which we have not ported yet.

**Comment by brotzeit** [comment]
How can I access the message box contents ?

**Comment by harryfei** [comment]
LGTM

**Comment by shaleh** [comment]
I don't know that you can @brotzeit

**Pull request merged**
