### PR TITLE
Re-order imports to minimal merge conflicts. Include a rustfmt config to keep it this way.

### PR DESCRIPTION
**Pull request by shaleh**
The config was generated with --dump-default-config. Then the values
for `reorder_imports` and `reorder_imports_group` were set to true.

Part of #412

### CODE REVIEW

**Comment by shaleh** [comment]
This config will sort all imports. The `reorder_import_groups` option means if we put imports in groups they will be honored. For instance:

    use std::thing;
    use libc::foo;
    use std::bar;

    use libc;
    use core::blah;

Will reorder to:

    use libc::foo;
    use std::bar;
    use std::thing;

    use core::blah;
    use libc;

What this means is we will still have some control over the order of imports even if they are being sorted. So we could have system crates, then external crates, then local crates and each sub group will be sorted.

**Comment by shaleh** [comment]
I did not commit the Rust changes because I wanted commentary before this is committed. I can update the PR when the time comes.

**Comment by jaccarmac** [comment]
The config need only contain values we explicitly want to set. Others will be set to their default values. In my opinion, this is preferable as it reduces the number of rules to keep in mind when reading the file or deciding on style changes.

Since the version of `rustfmt-nightly` is managed explicitly upgrades will not cause formatting to change in pull requests which do not update the Travis script, which is one objection I can see to that idea.

**Comment by shaleh** [comment]
Yeah, I was not sure either. This is why I dumped the default config and tweaked the values. Explicit versus implicit. Even if we moved to a new version of rustfmt the coding standard applied to remacs would remain (mostly) the same until we also updated the config.

**Comment by jaccarmac** [comment]
It's a tradeoff between being explicit and having to duplicate the effort of the `rustfmt` maintainers each time they update their list of default rules.

In any case, the two tweaks look good, regardless of how they are serialized :+1:

**Comment by shaleh** [comment]
Toggling to kick build

**Comment by shaleh** [comment]
I have run the new fmt. I also ordered the groups in order from system, remacs libs, local modules.

**Comment by shaleh** [comment]
Yes, we do. Each call to 'cargo fmt' needs its own config. We could store the config as a symlink but what happens on Windows?

**Comment by shaleh** [comment]
Actually, I figured out how to get `cargo fmt` to do the right thing. It should would be nice to have a simple `--config` option. But bah, usability is worthless :-)

**Pull request merged**
