### PR TITLE
Set process plist

### PR DESCRIPTION
**Pull request by tonyday567**
I had to include the s/from_raw/raw/ to test - let me know whether to take them out.

I wasn't really sure whether to go with an is_list, or reuse listp.

#354

### CODE REVIEW

**Comment by shanavas786** [comment]
> I had to include the s/from_raw/raw/ to test - let me know whether to take them out.

That is fixed by #416 , you can remove 2nd commit and rebase.

**Comment by tonyday567** [comment]
@shanavas786 thanks, removed that commit.

**Comment by shaleh** [comment]
We have switched to 'rustfmt-nightly'.

**Comment by tonyday567** [comment]
Refactored towards the conversation in #421 

I did have rustfmt-nightly, but `make rustfmt` was silently failing due to #423 issue.  Still not entirely sure I have rustfmt-nightly set up properly.

**Comment by shaleh** [comment]
Easy test. Add unindented code. Then run rustfmt on that file. It should improve.

On October 26, 2017 6:32:26 PM PDT, Tony Day <notifications@github.com> wrote:
>Refactored towards the conversation in #421 
>
>I did have rustfmt-nightly, but `make rustfmt` was silently failing due
>to #423 issue.  Still not entirely sure I have rustfmt-nightly set up
>properly.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Wilfred/remacs/pull/421#issuecomment-339847107

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request merged**
