### PR TITLE
Fix buffer-list showing duplicate entries

### LINKED ISSUE #994: buffers shown twice in helm buffer
I just cloned remacs and build the binary. 

I'm using Spacemacs, and found that in Helm buffer all buffers (except Messages) are shown twice.

### PR DESCRIPTION
**Pull request by nitishch**
Fixes #994.

The issue was a simple logical error. Do I need to have a test for this? This doesn't seem like an issue that might pop up again.

### CODE REVIEW

**Comment by shaleh** [comment]
@Nitishch is if I apply this to my PR #1033 to refresh this function?

**Comment by nitishch** [comment]
> @nitishch is it ok if I apply this to my PR #1033 to refresh this function?

Sure. I didn't see that PR.

**Comment by shaleh** [comment]
I added a simple test that `(buffer-list (selected-frame))` is unique.

**Comment by shaleh** [comment]
Closing in lieu of #1033

**Pull request closed without merging**
