### PR TITLE
port marker functions

### PR DESCRIPTION
**Pull request by brotzeit**

### CODE REVIEW

**Comment by brotzeit** [comment]
I don't see the problem...

**Comment by shaleh** [comment]
On this plus side it fails for me too. So it is not just a Travis issue.

**Comment by brotzeit** [comment]
I didn't look at the struct order. Probably I need to use getters and setters.

**Comment by shaleh** [comment]
Ah, that would do it :-(

**Comment by shaleh** [comment]
We really need to get @db48x 's PRs in

**Comment by brotzeit** [comment]
I didn't use an equivalent to `live_buffer`. That was the problem.

**Pull request merged**
