### PR TITLE
Set up 'workspace' section in cargo config

### LINKED ISSUE #1254: Set up a 'workspace' in our Cargo config
This will enable more cargo tools to work with our crates.

https://learning-rust.github.io/docs/d5.workspaces.html

### PR DESCRIPTION
**Pull request by daichimukai**
remacs-lib, remacs-util and remacs-macros are now members of the remacs workspace. These crates share the same Cargo.lock, output directory and profiles. We drop `lto = true` option until we start to self-host this project as a Rust crate.

Closes #1254.

### CODE REVIEW

**Comment by agraven** [comment]
We want to track the new shared Cargo.lock, right?

**Comment by daichimukai** [comment]
@agraven Yes we do, and in my understand the shared lock file is `rust_src/Cargo.lock` which we are already tracking!

**Comment by agraven** [comment]
Ah, I forgot we're already tracking that file. Whoops.

**Comment by daichimukai** [comment]
Fixed a conflict.

**Pull request merged**
