### PR TITLE
Added .elc files to the list of files that get removed by 'make clean'.

### PR DESCRIPTION
**Pull request by setupminimal**
This is the fix for Issue #20.

### CODE REVIEW

**Comment by setupminimal** [comment]
Thank you! Is there anything else I have to do to get these changes merged?

**Comment by Wilfred** [comment]
Nope, just wait for the Travis build to go green.

**Comment by Wilfred** [comment]
👍

**Comment by kennethkalmer** [comment]
@setupminimal @Wilfred the readme needs an update :)

I wanted to tackle this one and luckily I searched the issues first

**Comment by Wilfred** [comment]
@kennethkalmer woops, sorry about that! Fixed in e4b68116f2.

**Pull request merged**
