### PR TITLE
Build on OS X too

### PR DESCRIPTION
**Pull request by Wilfred**
Related: #38

### CODE REVIEW

**Comment by rogermarlow** [comment]
The build is failing because MacOSX doesn't have makeinfo. I think it's part of the texinfo set of gnu tools. Do we add installation of this to the travis config?

**Comment by c-nixon** [comment]
alternativelys adding --without-makeinfo to the call to configure might fix it

**Comment by rogermarlow** [comment]
According to this build log https://travis-ci.org/Wilfred/remacs/jobs/192527626 it is trying to make docs

```
checking whether C compiler handles -Wno-unknown-attributes... yes
checking whether make supports nested variables... (cached) yes
checking whether ln -s works for files in the same directory... yes
checking for install-info... /usr/bin/install-info
checking for gzip... /usr/bin/gzip
configure: error: You do not seem to have makeinfo >= 4.13, and your
source tree does not seem to have pre-built manuals in the 'info' directory.
Either install a suitable version of makeinfo, or re-run configure
with the '--without-makeinfo' option to build without the manuals. 
make: *** [Makefile] Error 1
make check failed
```

**Comment by c-nixon** [comment]
@rogermarlow The change in #83 fixes the build up to temacs, then it all falls apart for what looks like an actual bug somewhere

**Comment by rogermarlow** [comment]
@c-nixon yep, looks like its now hitting #38 or something very similar. So this PR looks good to me.

**Comment by Wilfred** [comment]
Wow, the build is much slower now we're building on two platforms. I've dropped Rust beta to try to help.

**Comment by Wilfred** [comment]
@pnkfelix I've got all the ERT tests running on OS X now, but 'cargo test' is failing:

```
cargo test --manifest-path ./rust_src/Cargo.toml

   Compiling libc v0.2.17

   Compiling lazy_static v0.2.2

   Compiling alloc_unexecmacosx v0.1.0 (file:///Users/travis/build/Wilfred/remacs/rust_src/alloc_unexecmacosx)

   Compiling remacs v0.1.0 (file:///Users/travis/build/Wilfred/remacs/rust_src)

error: linking with `cc` failed: exit code: 1

  |

  = note: "cc" "-m64" "-L" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib" "/Users/travis/build/Wilfred/remacs/./rust_src/target/debug/deps/remacs-a443f770ab176721.0.o" "-o" "/Users/travis/build/Wilfred/remacs/./rust_src/target/debug/deps/remacs-a443f770ab176721" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/travis/build/Wilfred/remacs/./rust_src/target/debug/deps" "-L" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libtest-551a7b69d9c2ff2f.rlib" "/Users/travis/build/Wilfred/remacs/rust_src/target/debug/deps/liblazy_static-2a16fcec40d2bdf3.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libgetopts-adadcf1010f2a10b.rlib" "/Users/travis/build/Wilfred/remacs/rust_src/target/debug/deps/liblibc-fc5952bc92157004.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libterm-6601acf7aa3689cb.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libstd-a260b5db713b337f.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-18bf5d50673f1daa.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libunwind-6b24ec54aa474d14.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/librand-664091cbac310259.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libcollections-4e19d5a43d7fdd2c.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/liballoc-99e0cdfb2e11773a.rlib" "/Users/travis/build/Wilfred/remacs/rust_src/target/debug/deps/liballoc_unexecmacosx-19c2c4e0a6e57f36.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/liblibc-109501e572ed7296.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libstd_unicode-49cd3c7af2b2f27f.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libcore-f1125930d2c15bcd.rlib" "/Users/travis/rust/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-594db3b2ae45efeb.rlib" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m"

  = note: Undefined symbols for architecture x86_64:

            "_unexec_free", referenced from:

                ___rust_deallocate in liballoc_unexecmacosx-19c2c4e0a6e57f36.rlib(alloc_unexecmacosx-19c2c4e0a6e57f36.0.o)

            "_unexec_realloc", referenced from:

                ___rust_reallocate in liballoc_unexecmacosx-19c2c4e0a6e57f36.rlib(alloc_unexecmacosx-19c2c4e0a6e57f36.0.o)

            "_unexec_malloc", referenced from:

                ___rust_allocate in liballoc_unexecmacosx-19c2c4e0a6e57f36.rlib(alloc_unexecmacosx-19c2c4e0a6e57f36.0.o)

          ld: symbol(s) not found for architecture x86_64

          clang: error: linker command failed with exit code 1 (use -v to see invocation)

          

error: aborting due to previous error
```

any ideas?

**Comment by jeandudey** [comment]
@Wilfred you may need to reemplaze
```rust
#[cfg(target = "macos")]
extern crate alloc_unexecmacosx;
```
with
```rust
#[cfg(all(not(test), target = "macos"))]
extern crate alloc_unexecmacosx;
```

**Comment by Wilfred** [comment]
@jeandudey perfect, that did the trick!

**Pull request merged**
