### PR TITLE
port the DEFUN concat of fns.c

### PR DESCRIPTION
**Pull request by purplejacket**
usage: (concat &rest SEQUENCES)

### CODE REVIEW

**Comment by shaleh** [comment]
We have been trying to either a) write tests or b) migrate tests.

**Comment by purplejacket** [comment]
BTW, I intend to write tests for these last few changes, but those tests are failing because the C language concat function of fns.c hasn't been ported yet.  I want to port all the callers of this function first as it's a rather long and complicated function, then port that one, then write test coverage.

**Comment by shaleh** [comment]
We have been writing all tests in elisp at this point. `remacs/test/src` matches the C source tree and `remacs/test/rust_src` matches the Rust src.

**Comment by shaleh** [comment]
And yes, Travis appears to be making updates and we need to catch up.

**Comment by Wilfred** [comment]
@purplejacket I've added you as a collaborator, so you can also review PRs if you wish :) :sparkles:

**Pull request merged**
