### PR TITLE
Replace LispObject::from_raw with std::convert::From implementation

### PR DESCRIPTION
**Pull request by shanavas786**

### CODE REVIEW

**Comment by brotzeit** [comment]
I would prefer to only change `from_raw` to `from`. IMO the verbosity of the other method names is helpful.

**Comment by shaleh** [comment]
Agreed. Rust is about explicit types. Why hide them?

**Comment by birkenfeld** [comment]
I have to agree with @brotzeit - to me this seems to stretch the purpose of `From` too far.

**Comment by birkenfeld** [comment]
Next question: should we now replace `LispObject::from(x)` with `x.into()` which is less wordy?

**Comment by shaleh** [comment]
That it is a little more interesting:

    #[inline]
    pub fn point_marker(self) -> LispObject {
        self.pointm.into()
    }

Versus current style

    #[inline]
    pub fn point_marker(self) -> LispObject {
        LispObject::from(self.pointm)
    }

**Comment by shaleh** [comment]
And:

    #[lisp_fn]
    pub fn selected_window() -> LispObject {
        unsafe { current_window }.into()
    }

**Comment by shaleh** [comment]
Tweaking this:

    /// Internal function to get a displayable string out of a Lisp string.
    fn display_string<LO: Into<LispObject>>(obj: LO) -> String {
        let mut s = obj.into().as_string().unwrap();
        let slice = unsafe { slice::from_raw_parts(s.data_ptr(), s.len_bytes() as usize) };
        String::from_utf8_lossy(slice).into_owned()
    }

Also makes this possible:

display_string(unsafe { SYMBOL_NAME(self.to_raw()) })

**Comment by brotzeit** [comment]
@Wilfred what do you think ?

**Comment by shaleh** [comment]
Style guideline time?

Use `into` for the examples I showed where the value is being returned and it is clear that the Lisp_Object is being upcast into a Rust LispObject. Otherwise, use ::from() within functions?

**Pull request merged**
