### PR TITLE
Restore proper line number attributions for lisp_fn errors.

### PR DESCRIPTION
**Pull request by pipcet**
#710 didn't actually preserve those, since it parsed `fn_item` back into tokens. The explicit type annotation appears to be required.

It would be nice to add a test for this.

### CODE REVIEW

**Comment by Wilfred** [comment]
Woops, meant to approve.

**Comment by shaleh** [comment]
A demo/test program in the macro's crate which has a purposeful compilation error should suffice. The test would be compile and save output. Compare that to a expected output.

**Comment by pipcet** [comment]
How would that work? `rustc` requires special parameters, and `cargo` would have to use an extra crate, or at least a feature, and be very slow, right?

**Comment by shaleh** [comment]
@pipcet this one is no longer needed, right?

**Pull request closed without merging**
