### PR TITLE
Fix issue with backup files.

### PR DESCRIPTION
**Pull request by jaccarmac**
Was introduced during the last merge from GNU with a commit that attempted to fix handling of backup files with Tramp + Windows, I believe. I can save again with these patches applied.

### CODE REVIEW

**Comment by jaccarmac** [comment]
Used the `admin/gitmerge.el` script for this, not sure if that's how to integrate upstream changes? If not let me know how and I'll re-run the merge.

Merges and reverts don't always play nice, hopefully that won't cause problems here. The revert came from upstream, so my fingers are crossed.

**Comment by jaccarmac** [comment]
Not sure why that test's failing, don't see it failing on my end.

I merged a merge commit slightly further forward and it seems to have nuked the list of commits in the PR while leaving the changes. Is that good or bad?

**Comment by jaccarmac** [comment]
Merged 9d7f0e27e0592132c1b5b9c280192333eaf288b8 to be clear.

**Comment by Wilfred** [comment]
It looks like you've ended up with squashed commits somehow, as 12ddb1c48fdf461a19140dca8e67c3e49ca7128b is now a single commit attributed to you. That's bad as it prevents us seeing who wrote those lines, and when.

Great spot on the 'expected fail' test, by the way :+1:

**Comment by jaccarmac** [comment]
Credit to @db48x on that, they mentioned it and I forgot until this aft.

Re: The commit, I'll rerun the merge. I didn't squash manually, that was `gitmerge.el`'s doing. Regardless...

**Comment by jaccarmac** [comment]
Looks like GitHub doesn't like branch rename followed by force push. New PR is up.

**Pull request closed without merging**
