### PR TITLE
rustup-toolchain will be installed when running ./autogen.sh

### PR DESCRIPTION
**Pull request by rofrol**
```bash
remacs$ ./autogen.sh
Checking Rust toolchain install ...
info: syncing channel updates for 'nightly-2018-09-09-x86_64-unknown-linux-gnu'
info: latest update on 2018-09-09, rust version 1.30.0-nightly (0198a1ea4 2018-09-08)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
...
```

### CODE REVIEW

**Comment by shaleh** [comment]
autogen.sh is really not the right place for this is it? autogen.sh is just meant to create the autotools files so configure can be run.

**Comment by rofrol** [comment]
I just wanted to point that this note in Readme is redundant as this command will get correct toolchain

https://github.com/Wilfred/remacs/blob/a171e148b2887d78a5da94845dd813b455f79cc8/autogen.sh#L140

**Comment by brotzeit** [comment]
I think this part should say something about not changing the project's toolchain since it is automatically taken from the file rust-toolchain.

**Comment by rofrol** [comment]
@brotzeit I think it says something similar:

>Remacs uses unstable Rust features, so you will need to use nightly. The file `rust-toolchain` indicates the correct version to install; rustup will use that version as long as you are in the Remacs repository

**Comment by brotzeit** [comment]
IMO the important part here is that it is handled automatically.

**Comment by rofrol** [comment]
Something like:

>Remacs uses unstable Rust features, so you will need to use nightly. The file `rust-toolchain` indicates the correct version to install; rustup will automatically install and use that version.

**Comment by brotzeit** [comment]
IMO that's good. But I would add at the end something like "don't override the project's toolchain manually". AFAIK this breaks the automatic installation.

**Comment by shaleh** [comment]
Correct, a manual override should have an old school BLINK tag style *DONT DO IT, ITS A TRAP!*

**Pull request merged**
