### PR TITLE
Document how to set the correct rust toolchain

### PR DESCRIPTION
**Pull request by Wilfred**
This should help with #752.

### CODE REVIEW

**Comment by shaleh** [comment]
You should not have to do this. Just running make at the top of tree will detect and install the correct toolchain.

**Comment by shaleh** [comment]
We removed it from the documentation because of the confusion. Maybe we should add it as a separate optional step. Or maybe this only happens on Windows?

**Comment by Wilfred** [comment]
I found I needed to do this after 'rustup update'. I'll dig further.

**Comment by jaccarmac** [comment]
```
darweshi :: ~/src/src/github.com/Wilfred/remacs » rustc --version
rustc 1.25.0-nightly (29c8276ce 2018-02-07)
darweshi :: ~/src/src/github.com/Wilfred/remacs » cd
darweshi :: ~ » rustc --version
rustc 1.28.0-nightly (952f344cd 2018-05-18)
darweshi :: ~ »
```

Works for me as well, really weird that you're encountering an issue with it.

**Comment by Wilfred** [comment]
Further confusing matters, overrides don't apply to child directories:

```
$ rustc --version
rustc 1.25.0-nightly (29c8276ce 2018-02-07)
~/projects/remacs 
$ cd rust_src 
~/projects/remacs/rust_src 
$ rustc --version
rustc 1.26.0-nightly (517f24025 2018-03-31)
```

This makes doing `cargo check` less convenient.

**Comment by shaleh** [comment]
@Wilfred, does moving the `rust-toolchain` file into `rust_src` help?

**Comment by jaccarmac** [comment]
Do you have any manual overrides setup? Last I checked child directories were fine, but I'll check again on my machine in a couple hours.

**Comment by jaccarmac** [comment]
```
darweshi :: ~/src/src/github.com/Wilfred/remacs » rustc --version
rustc 1.25.0-nightly (29c8276ce 2018-02-07)
darweshi :: ~/src/src/github.com/Wilfred/remacs » cd rust_src 
darweshi :: ~/src/src/github.com/Wilfred/remacs/rust_src » rustc --version
rustc 1.25.0-nightly (29c8276ce 2018-02-07)
darweshi :: ~/src/src/github.com/Wilfred/remacs/rust_src » rustup override list
no overrides
darweshi :: ~/src/src/github.com/Wilfred/remacs/rust_src » rustup --version
rustup 1.11.0 (e751ff9f8 2018-02-13)
darweshi :: ~/src/src/github.com/Wilfred/remacs/rust_src »
```

I would make sure you aren't accidentally setting up conflicting overrides. Beyond that it may just be works-on-my-machine and in that case I'm sorry for the red herring.

**Comment by Wilfred** [comment]
You're probably right. I'll reopen this if I can reliably reproduce.

**Comment by shaleh** [comment]
We might want to document that setting the override is not necessary and can cause problems if we update the rust-toolchain file.

**Pull request closed without merging**
