### PR TITLE
Add init_modules macro 

### PR DESCRIPTION
**Pull request by shanavas786**

### CODE REVIEW

**Comment by shaleh** [comment]
I can take over leave this one. However, I think this would be a great idea for the `defsubr` stanzas at the end of each module.

**Comment by shaleh** [comment]
See #454

**Comment by shaleh** [comment]
@shanavas786 I absorbed this in #456. The `rust_init_syms` function in lib.rs is now generated so I did not need the macro.

**Comment by shanavas786** [comment]
Closing in favor of #456

**Pull request closed without merging**
