### PR TITLE
Add define_functions macro.

### PR DESCRIPTION
**Pull request by jeandudey**
I refactored the `rust_init_syms` function, i added the define_functions
macro. It handles the definition of the `rust_init_syms` function, also
it eventually could be used to export C functions and handle modules
definitions.

Also the `floatfns_init_syms` function was removed, the define_functions
allows us to initialize the symbols more cleanly without the need of another
function.

Signed-off-by: Jean Pierre Dudey <jeandudey@hotmail.com>

### CODE REVIEW

**Comment by Wilfred** [comment]
I'm definitely in favour of removing the separate function for defining float functions.

I worry that the macro (whilst definitely pretty) is a little too magical though. What do you think about moving the function definition out of the macro?

**Comment by jeandudey** [comment]
@Wilfred thanks for the feedback, i've thinked that too and tought it was magical, also it would allow us to define other `*_init_syms` functions. I'll change it

**Comment by jeandudey** [comment]
@Wilfred i've updated it :+1:

**Comment by jeandudey** [comment]
@Wilfred oops, i forgot to mention that i updated the README.md file

**Comment by Wilfred** [comment]
I'm closing this due to inactivity. If you're still interested, do feel free to open a new PR.

**Pull request closed without merging**
