### PR TITLE
Ported keymap-prompt with Tests.

### LINKED ISSUE #649: Port keymap-prompt from keymap.c
This is the next function that I'll be porting.

```c
DEFUN ("keymap-prompt", Fkeymap_prompt, Skeymap_prompt, 1, 1, 0,
       doc: /* Return the prompt-string of a keymap MAP.
If non-nil, the prompt is shown in the echo-area
when reading a key-sequence to be looked-up in this keymap.  */)
  (Lisp_Object map)
{
  map = get_keymap (map, 0, 0);
  while (CONSP (map))
    {
      Lisp_Object tem = XCAR (map);
      if (STRINGP (tem))
	return tem;
      else if (KEYMAPP (tem))
	{
	  tem = Fkeymap_prompt (tem);
	  if (!NILP (tem))
	    return tem;
	}
      map = XCDR (map);
    }
  return Qnil;
}
```

Things that are new to me are `CONSP`, `XCAR`, `STRINGP`, and `XCDR`. I bet can be able to figure these out.

### PR DESCRIPTION
**Pull request by accidentalrebel**
Successfully ported `keymap-prompt` from `keymap.c` with tests. Closes #649.

- The code works but I am unsure if the style I used is correct. 
- I learned that returning inside a for loop doesn't work so I had to pass it to the `result` variable so it can be returned by the function.
- I've also separated the Ffoo imports from the other function imports.

Thanks!

### CODE REVIEW

**Comment by shaleh** [comment]
`return` requires semicolons.

    pub fn keymap_prompt(map: LispObject) -> LispObject {
        let map = unsafe { LispObject::from_raw(get_keymap(map.to_raw(), false, false)) };
    
        for elt in map.iter_cars_safe() {
            if elt.is_string() {
                return elt;
            } else if keymapp(elt) {
                let tem = keymap_prompt(elt);
                if tem.is_not_nil() {
                    return tem;
                }
            }
        }
    
        LispObject::constant_nil()
    }

**Comment by accidentalrebel** [comment]
Oh.. Let me try that.

**Comment by accidentalrebel** [comment]
I tried it and it works! Fixed and pushed.

**Comment by accidentalrebel** [comment]
Awesome. And the branch can easily be deleted. Sweet.

**Pull request merged**
